### ISSUE TITLE
 ImportError: cannot import name batching

### ISSUE THREAD

**Issue by saurabhvyas** [DeftWork/rpi-tensorflow#3]
so I just installed the image, and ran the container, and tf.contrib modules dont seem to be working ...

```
    20 
     21 # Add projects here, they will show up under tf.contrib.
---> 22 from tensorflow.contrib import batching
     23 from tensorflow.contrib import bayesflow
     24 from tensorflow.contrib import cloud

ImportError: cannot import name batching

```

**Comment by saurabhvyas** [comment]
Sorry, It was problem from my end, I didnt update my dataset api imports , to make it work with 1.5 API
